### ISSUE TITLE
Uses version string directly for publishing instead of Minecraft version

### ISSUE THREAD

**Issue by sciwhiz12** [ParchmentMC/Blackstone#2]
The Blackstone buildscript uses the `blackstone_targets_mc_version` project property for Lodestone to determine what Minecraft version to use, as well as the version used when publishing the Maven artifact.

Lodestone also not only accepts Minecraft versions, but also the special values `latest_release`, `latest_snapshot`, and `latest`, which means the following, respectively: the latest release as determined by `latest.release` in the launcher manifest, the latest snapshot as determined by `latest.snapshot` in the manifest, and the actual latest version (determined by comparing the latest release and snapshot's release dates).

However, because the version string from the aforementioned project property is directly passed both to Lodestone and the publishing artifact, it means that if something runs the buildscript with the `blackstone_targets_mc_version` set as one of the special values (such as Blackstone's CI and `latest`), it will also use the special value for publishing instead of the actual Minecraft version which the artifact was published for.

For example, as of writing the special value `latest` resolves to the Minecraft version 1.17. However, running Blackstone's CI with this special value will lead to the published artifact being `org.parchmentmc.data:blackstone:latest`, instead of the expected ``org.parchmentmc.data:blackstone:1.17`.

_Potential solution:_ One of Lodestone's tasks (either a pre-existing one or a new one for this purpose) should have an output provider (`@Internal` getter) for the actual Minecraft version in use. Then the publishing tasks (`AbstractPublishToMaven` and subclasses) should be configured to hold a `doFirst` task that modifies the publication to have the correct version.

**Comment by marchermans** [comment]
This is actually a good idea.
But not something high on the prio list I think.
