### ISSUE TITLE
Disable Gson HTML escaping for exported data

### ISSUE THREAD

**Issue by alcatrazEscapee** [ParchmentMC/Blackstone#4]
Example:
```json
"moj": "(Ljava/util/function/Consumer\u003c-Lnet/minecraft/core/SectionPos;\u003e;)Z"
```

Note:
- Need to assert / test that parsing escaped JSON, and non-escaped JSON both works correctly. Essentially backwards compat for newer tooling with existing exports.

**Comment by SizableShrimp** [comment]
Fixed in ParchmentMC/Lodestone#1 and e0b6cedd6e5597eb141b8e5f3aea9219bf37b006
